name: Zip src directory on push to main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip src directory
      env: 
        TAG_NAME : ${{github.ref_name}}
      run: |
        cd src
        zip -r ../plg_includehtml-${TAG_NAME}.zip .

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: plg_includehtml-${{github.ref_name}}.zip
        path: plg_includehtml-${{github.ref_name}}.zip
