name: Package and release the plugin

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZIP_BASENAME : plg_content_includehtml
      TAG_NAME : ${{ github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip src directory
      run: |
        cd src
        zip -r ../${ZIP_BASENAME}-${TAG_NAME}.zip .

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.ZIP_BASENAME }}-${{ env.TAG_NAME }}.zip

